### ISSUE TITLE
Some digital pins for Leonardo are wrong

### ISSUE THREAD

**Issue by bperrybap** [Bouni/Arduino-Pinout#3]
The digital pins #s for the analog pins are incorrect.
The current image shows A0-A5 as digital pins 14 to 19.
This is incorrect. The variant file maps A0 to A5 as digital pins 18 to 23.

Also the digital pin numbers for ICSP pins are missing:
SS is digital pin 17 
(which unfortunately is not available on board for use and can only blink a LED)

MOSI is digital pin 16
MISO is digital pin 14
SCK is digital pin 15

**Comment by stahlnow** [comment]
+1

**Comment by Bouni** [comment]
Hi,

feel free to submit a pull request! I made these diagrams using Inkscape which is open source, so everybody can contribute!
Afterwards one can use the convert.ps1 to automatically generate the .png files from the .svg files.

**Comment by bperrybap** [comment]
I created two pull requests. One for the Leonardo pin fixes, and another for converting the README to use relative links for the images so that the come from the local repository rather than this one.
See pull requests for more info.

**Comment by bperrybap** [comment]
I believe that this has been resolved.
